export const productPlans = {
  free: {
    code: "free",
    name: "Free",
    priceKopecks: 0,
    includedSeconds: 30 * 60,
    queueWeight: 1,
    activeProjects: 1,
    sourceRetentionDays: 3,
    outputRetentionDays: 3,
    exportHeight: 1280,
    watermark: true,
  },
  start: {
    code: "start",
    name: "Start",
    priceKopecks: 29_900,
    includedSeconds: 60 * 60,
    queueWeight: 1.25,
    activeProjects: 1,
    sourceRetentionDays: 30,
    outputRetentionDays: 90,
    exportHeight: 1920,
    watermark: false,
  },
  creator: {
    code: "creator",
    name: "Creator",
    priceKopecks: 99_000,
    includedSeconds: 300 * 60,
    queueWeight: 2,
    activeProjects: 2,
    sourceRetentionDays: 90,
    outputRetentionDays: 365,
    exportHeight: 1920,
    watermark: false,
  },
  studio: {
    code: "studio",
    name: "Studio",
    priceKopecks: 299_000,
    includedSeconds: 1_000 * 60,
    queueWeight: 3,
    activeProjects: 5,
    sourceRetentionDays: 180,
    outputRetentionDays: 365,
    exportHeight: 1920,
    watermark: false,
  },
} as const;

export const minutePackages = [
  { code: "minutes_60", seconds: 60 * 60, priceKopecks: 39_000, expiresDays: 365 },
  { code: "minutes_180", seconds: 180 * 60, priceKopecks: 99_000, expiresDays: 365 },
  { code: "minutes_360", seconds: 360 * 60, priceKopecks: 169_000, expiresDays: 365 },
] as const;

export const mediaLimits = {
  free: { maxBytes: 2 * 1024 ** 3, maxDurationSeconds: 60 * 60 },
  paid: { maxBytes: 10 * 1024 ** 3, maxDurationSeconds: 4 * 60 * 60 },
  uploadPartBytes: 12 * 1024 ** 2,
  minimumScratchFreeBytes: 8 * 1024 ** 3,
} as const;

export const defaultStyleConfig = {
  schemaVersion: 1 as const,
  layout: { mode: "auto" as const, safeFallback: "static_crop" as const },
  subtitles: {
    enabled: true,
    mode: "active_word" as const,
    preset: "clean" as const,
    fontFamily: "Manrope",
    fontSize: 58,
    fontWeight: 800,
    uppercase: false,
    maxWordsPerLine: 5,
    maxLines: 2,
    position: "bottom" as const,
    safeMarginPx: 160,
    align: "center" as const,
    color: "#ffffff",
    activeColor: "#10b8f4",
    outlineColor: "#06131a",
    outlinePx: 4,
    shadow: true,
    background: false,
    punctuation: true,
    emoji: false,
    censorWords: [],
  },
  silence: {
    enabled: true,
    minimumMs: 800,
    beforePaddingMs: 100,
    afterPaddingMs: 120,
    crossfadeMs: 30,
  },
  safeZones: ["shorts", "reels", "tiktok", "vk"] as const,
  export: {
    width: 1080,
    height: 1920,
    fps: 30,
    videoCodec: "h264" as const,
    audioCodec: "aac" as const,
    videoBitrateKbps: 6500,
    audioBitrateKbps: 160,
    watermark: false,
  },
};

export type PlanCode = keyof typeof productPlans;
